import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [content, setContent] = React.useState([`Hej hej, write 'help' to navigate ⚑`])
  const [command, setCommand] = React.useState('')
  const aboutJinbread = "Jinjae Lee is a senior product designer / product design lead at flex, a HR SaaS startup based in Seoul. He worked at Hyundai Motor Group, Above Agency as an interaction designer."
  const helpText = ["→ about - summary of jinjae", "→ help - command list", "→ cd location - move to specific folder"]
  const [path, setPath] = React.useState('~')

  return (
    <div className={styles.container}>
      <Head>
        <title>Jinbread works in progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>



        <p className={styles.title}>
          Jinbread works{' '}
          <div className={styles.tag}>in progress</div>
        </p>
        <p className={styles.description}>Interaction designer by day, <br/> creative coder and writer by night.</p>

<div>

        <div>
          {content.map( (item, i) => {
            return <div className={styles.terminal} key={i}>{item}</div>
          })}
        </div>

        <form className={styles.form}
          onSubmit={(e) => {
            if(command == "about") {
                setContent([...content, "→  " + path + " "+ command, aboutJinbread])
            } else if(command == "help") {
              setContent([...content, "→  " + path + " "+ command, ...helpText])
            } else if(command.split(' ')[0] == "cd") {
              setContent([...content, "→  " + path + " "+ command])
              setPath(command.split(' ')[1] + ' ')
            } else {
              setContent([...content, `command not found: ${command}`])
            }

          // console.log(content)
          setCommand("")
          e.preventDefault();
          
        }}>

          <div className={styles.terminal} style={{display: "inline-block", color: "cyan", marginRight: 4, marginTop: 8}} >{"→  "}{path}{" "}</div> <input className={styles.input} value={command} onChange={(e) => setCommand(e.target.value)} />
          {/* <button className={styles.button} type="submit">Enter</button> */}
        </form>
        </div>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
