import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [content, setContent] = React.useState(['Write Anything'])
  const [command, setCommand] = React.useState('')
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Jinbread works in progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        

        <p className={styles.title}>
          Jinbread works{' '}
          <div className={styles.tag}>in progress</div>
        </p>
        <p className={styles.description}>Interaction designer by day, <br/> creative coder and writer by night.</p>

        <form className={styles.form}
          onSubmit={(e) => {
          setContent([...content, command])
          // console.log(content)
          setCommand("")
          e.preventDefault();
          
        }}>

          <input className={styles.input} value={command} onChange={(e) => setCommand(e.target.value)} />
          <button className={styles.button} type="submit">Enter</button>
        </form>

        <div>
          {content.map( (item, i) => {
            return <div className={styles.terminal} key={i}>{item}</div>
          })}
        </div>

      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
